import AppKit
import Foundation

/// Recognises pasteboard contents that must never be recorded.
///
/// Password managers (1Password, Bitwarden, Keychain Access, KeePassXC…) mark
/// their pasteboard writes with the community `org.nspasteboard.*` markers.
/// Honouring them is the difference between a clipboard manager and a plaintext
/// password logger.
enum PasteboardPrivacy {
    /// Set by any app that considers its pasteboard content secret.
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    /// Set by apps that write to the pasteboard on the user's behalf.
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    /// Set by apps that want the write to stay transient.
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")

    /// Bundle identifiers whose copies we never record, regardless of markers.
    static let excludedBundleIdentifiers: Set<String> = [
        "com.agilebits.onepassword",
        "com.agilebits.onepassword4",
        "com.agilebits.onepassword7",
        "com.1password.1password",
        "com.apple.keychainaccess",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
        "com.lastpass.LastPass",
        "in.sinew.Enpass-Desktop",
        "com.dashlane.dashlanephonefinal"
    ]

    /// True when the current pasteboard contents are marked secret or transient.
    static func isConcealed(_ pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains(concealed)
            || types.contains(transient)
            || types.contains(autoGenerated)
            || types.contains(where: { $0.rawValue == "com.agilebits.onepassword" })
    }

    static func isExcluded(bundleIdentifier: String?) -> Bool {
        guard let bundleIdentifier else { return false }
        return excludedBundleIdentifiers.contains(bundleIdentifier)
    }

    /// Marks our own writes so other clipboard managers skip them when asked to.
    static func markAsAutoGenerated(_ pasteboard: NSPasteboard) {
        pasteboard.setData(Data(), forType: autoGenerated)
    }
}
