import AppKit
import Foundation

/// Puts clips on the system pasteboard.
///
/// CopyWell deliberately does **not** synthesise the ⌘V keystroke. Doing so
/// requires the Accessibility permission, which is a common reason for Mac App
/// Store rejection for clipboard utilities and asks the user for blanket
/// control of their Mac in exchange for saving one keypress.
///
/// Instead, choosing a clip puts it on the pasteboard and returns focus to the
/// app the user came from, so ⌘V lands immediately. For insertion without any
/// keypress at all, CopyWell ships a Service ("Paste from CopyWell"), which is
/// the mechanism macOS sanctions for one app to hand text to another and needs
/// no permission whatsoever.
@MainActor
enum PasteService {
    /// The app that was frontmost before our palette appeared.
    private(set) static var previousApp: NSRunningApplication?

    static func rememberFrontmostApp() {
        let ours = NSRunningApplication.current.processIdentifier
        if let front = NSWorkspace.shared.frontmostApplication, front.processIdentifier != ours {
            previousApp = front
        }
    }

    /// Keeps `previousApp` current at all times, so focus can always be handed
    /// back to the right place.
    static func beginTrackingFrontmostApp() {
        NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification,
            object: nil,
            queue: .main
        ) { note in
            guard let app = note.userInfo?[NSWorkspace.applicationUserInfoKey] as? NSRunningApplication,
                  app.processIdentifier != NSRunningApplication.current.processIdentifier else { return }
            MainActor.assumeIsolated { previousApp = app }
        }
        rememberFrontmostApp()
    }

    /// Writes `content` to the pasteboard and returns focus to the previous app,
    /// leaving the user one ⌘V away.
    static func deliver(_ content: PasteContent, plainText: Bool = false) {
        write(content, plainText: plainText)
        SoundPlayer.play(.pasted)
        previousApp?.activate()
    }

    /// Writes to the pasteboard without touching focus.
    static func write(_ content: PasteContent, plainText: Bool = false) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        switch content {
        case .text(let string):
            pasteboard.setString(string, forType: .string)
        case .richText(let string, let rtf):
            if plainText || rtf == nil {
                pasteboard.setString(string, forType: .string)
            } else if let rtf {
                pasteboard.setData(rtf, forType: .rtf)
                pasteboard.setString(string, forType: .string)
            }
        case .image(let data):
            if let image = NSImage(data: data) {
                pasteboard.writeObjects([image])
            }
        }
        // Last, after the content: marks the write as ours so the monitor does
        // not record it again, and so other clipboard managers can skip it.
        PasteboardPrivacy.markAsAutoGenerated(pasteboard)
    }
}

enum PasteContent {
    case text(String)
    case richText(String, Data?)
    case image(Data)
}
